- op: replace
  path: /metadata/name
  value: test-app-prd
- op: replace
  path: /spec/replicas
  value: 3
- op: add
  path: /metadata/labels/version
  value: prd
- op: add
  path: /spec/template/metadata/labels/version
  value: prd
- op: replace
  path: /spec/template/spec/containers/0/name
  value: test-app-prd-container
- op: add
  path: /spec/selector/matchLabels/version
  value: prd
