apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: test-app
          image: naveen023/test-python-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
