apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-app-dev
resources:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: Namespace
      name: test-python
    path: ./namespace-patch.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: python-test-app
    path: ./deployment-patch.yml
